version: '3.8'

services:
  api:
    container_name: nestjs-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    command: npm run start:dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge